### ISSUE TITLE
UML z kodu obecnego

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#43]
Utworzenie diagramu UML z istniejącego kodu. 
Przeanalizowanie go pod kątem **słabych** i **mocnych** stron.
Diagram UML wstaw proszę jako odpowiedź na ten issue wraz z ww. analizą.

**Comment by KowalikJakub** [comment]
Gdyby to nie było oczywiste, to należy zrobić to w jakimś programie.
Podejrzewam że vs powinien mieć coś do tego.

**Comment by Kodeman010** [comment]
Faktycznie były typy, ale nie widzę zawierania
![uml](https://user-images.githubusercontent.com/20133604/47255139-92d83700-d46c-11e8-9437-4d0da4f962e9.png)

**Comment by KowalikJakub** [comment]
Poszukaj jeszcze czy nie da się tego zrobić proszę. I nie musisz usuwać moich komentarzy xD

**Comment by Kodeman010** [comment]
Usuwam, bo usunąłem stare zdjęcie by nikogo nie mylić, to Twój komentarz bez mojej wiadomości nie miał sensu

**Comment by KowalikJakub** [comment]
A racja, to nie usuwaj :D

**Comment by Kodeman010** [comment]
czekaj co?

**Comment by Kodeman010** [comment]
Ogólnie większość klas można przerobić na Scriptable objects, ale nie ma sensu, jeśli i tak nie będziemy już tych klas ruszać.
Natomiast takie rzeczy jak broń, którą będziemy robić od nowa, można już zrobić za pomocą SO.
Możemy również wprowadzić wzorzec projektowy "1 zmienna, 1 Scriptable object", aby przechowywać zmienne przydatne do UI. Dzięki temu otrzymamy coś na wzór wzorca MVVM.

**Comment by KowalikJakub** [comment]
@Kodeman010 To jeszcze do obgadania co konkretnie zrobimy, mam już kilka pomysłów w tym MVVM.
