### ISSUE TITLE
Ustrukturyzowanie folderów w projekcie

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#44]
Folder w którym należy tego dokonać to [Project](https://github.com/Sweaty-Bacon-Ducks/Steamy/tree/master/Project)

Powinno być tak (przykład):
- Prefabs
  - Broń.prefab
- Sprites
  - Broń.png

Wiele folderów jest gdzieś rozsianych i pliki są nie tam gdzie trzeba.
Należy je powstawiać w odpowiednie miejsca i zmienić nazwę jeśli trzeba.

**Comment by Kodeman010** [comment]
Nie zmieniałem tylko folderu effects examples, bo wygląda jak zbiór placeholderów.

**Comment by KowalikJakub** [comment]
Zaakceptowałem #50 więc zamykam to zgłoszenie
