### ISSUE TITLE
Animacje postaci

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#46]
Utworzenie animacji dla modeli 3D z #45

**Comment by MartinWoad** [comment]
Ulepszono AnimationController. Jest on daleki od doskonałości, ale spełnia swoją funkcję. Będzie w przyszłości udoskonalany.

Parametry i ich zastosowanie:

- **speedPercen**t (0.0f - 1.0f) - Reguluje prędkość animacji dla całego ciała w dowolnym kierunku. Dla wartości 0 postać nie porusza się.

- **headTiltPercent** (0.0f - 1.0f) - Reguluje odchylenie głowy postaci od pionu. Wartość jest ustalana dynamicznie przez skrypt.

- **runningPercent** (0.0f - 1.0f) - Reguluje stopień pomiędzy chodem, a biegiem postaci. 0 dla całkowitego chodu, 1 dla całkowitego biegu.

- **isFacingRight** (bool) - Reguluje, czy postać ma być zwrócona w prawo.
- **isGoingRight** (bool) - Reguluje, czy postać ma poruszać się w prawo.
- **isAiming** (bool) - Reguluje, czy postać ma celować.

**Comment by KowalikJakub** [comment]
Dobra super! To śmiało możesz PR robić, ja spróbuję dzisiaj wrzucić ten kod do klasy motionMode i zobaczyć jak to będzie działać. Dalej będzie można zrobić już synchronizację ruchu.

**Comment by KowalikJakub** [comment]
#57 Wydaje mi się że jest powiązany z tym zgłoszeniem.

**Comment by KowalikJakub** [comment]
@MartinWoad To zgłoszenie chyba można zamknąć. Na Twoje poprawki plus skakanie zrobimy osobne zgłoszenie
