### ISSUE TITLE
Eksploracja możliwości unity 3d w kontekście modelowania i animacji

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#49]
- Dodanie bazowego humanoidalnego modelu do Unity (Base)
- Wyeksportowanie animacji do Unity,
-Utworzenie animacji: jedna do chodzenia a druga do chodzenia z bronią sprawdzić czy da się to załatwić jedną animacją, 
- Zobacz jakie tekstury trzeba do materiałów zrobić, zrób jakieś testowe na bazowy model.

**Comment by MartinWoad** [comment]
Dodano bazowy humanoidalny model oraz animacje: stania w miejscu, chodzenia oraz biegania. 
Animacje można bez problemu na Unity blendować oraz wykonywać symultanicznie. Unity obsługuje tekstury dodane w Blenderze.
Należy jeszcze przygotować animację rąk podczas chodzenia z bronią oraz animację nóg, aby złożyć je w całość na Unity.

**Comment by KowalikJakub** [comment]
#51 Zmergowano więc tu zamykam.
