### ISSUE TITLE
Utworzenie interfejsu do systemu broni

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#55]
Należy utworzyć: 
- odpowiednie klasy do przechowywania informacji o broni (Modele oraz ViewModele)
- ustalić jeden interfejs do ich obsługi
- sprawić aby się serializowały wraz z postacią (odpowiednio zmodyfikować interfejs `CharacterModel`)
- testyyyyy jednostkowe!!!!

**Comment by KowalikJakub** [comment]
#61 Dodano weapon system

**Comment by KowalikJakub** [comment]
@Kodeman010 Proszę dodaj tutaj diagram UML i zamknij wątek.

**Comment by Kodeman010** [comment]
![49012248-2215f000-f179-11e8-9033-01005e35ae79](https://user-images.githubusercontent.com/20133604/49969625-46b7e900-ff29-11e8-9638-8496d4ec9aef.jpg)

**Comment by KowalikJakub** [comment]
❤️
