### ISSUE TITLE
Integracja animacji chodzenia z trzymaniem broni

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#57]
[Placeholdery](http://devassets.com/assets/modern-weapons/) są tam. 
Pobierz je i dodaj jeden wybrany i zrób dla niego animacje biegu (integracja z obecną animacją), odrzutu podczas strzelania, przeładowania.

**Comment by MartinWoad** [comment]
Trzymanie broni zintegrowano z chodzeniem. Pozostaje animacja przeładowania i odrzutu.

**Comment by KowalikJakub** [comment]
@MartinWoad ale to można w takim razie ten wątek zamknąć ponieważ dotyczył tylko integracji chodzenia i trzymania broni. Potem można będzie kolejny wątek zrobić dla animacji przeładowania i odrzutu.

**Comment by MartinWoad** [comment]
W takim razie zamykam.
