### ISSUE TITLE
Weapon System UML Diagram

### ISSUE THREAD

**Issue by Kodeman010** [Sweaty-Bacon-Ducks/Steamy#60]
Pierwsza wersja diagramu systemu broni:

![weaponsystem](https://user-images.githubusercontent.com/20133604/48974297-c3efec80-f054-11e8-846a-892eb84f6bc6.jpg)

**Comment by KowalikJakub** [comment]
Kilka poprawek: 
- zmiana nazw:
  - Weapon -> WeaponViewModel 
  - Melee -> MeleWeaponViewModel etc.
  - to samo po prawej stronie, *Data-> *Model
- w klasie Weapon brakuje pola WeaponData
- Klasa Weapon musi dziedziczyć po MonoBehaviour

A tak to jest git

**Comment by Kodeman010** [comment]
![weaponsystemfinished](https://user-images.githubusercontent.com/20133604/49012248-2215f000-f179-11e8-9033-01005e35ae79.jpg)

**Comment by KowalikJakub** [comment]
Dobra, jest super zamykam i otwieram nowe zgłoszenie na przeniesienie tego na kod.
