### ISSUE TITLE
Udostępnienie interfejsu do interakcji z kamerą gracza podczas rozgrywki

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#65]
Ustalić interfejs a następnie utworzyć przykładową implementację pozwalającą na wpływ na położenie kamery wzgędem gracza.

**Comment by Kodeman010** [comment]
Wstawiam wersję podstawową kamery. Pozwala na śledzenie celu i poruszanie kamery względem celu związane z celowaniem.

```
using UnityEngine;

public class CameraFollow : MonoBehaviour {

    private Camera cam;

    public Transform Target;

    public Vector3 Offset;
    public float MovementSpeed = 8f;
    public float MouseRange = 5f; // How much mouse affects camera position

    void Start()
    {
        cam = GetComponent<Camera>();
        //transform.eulerAngles = new Vector3(70, 0, 0); for rotation if needed
    }

    void Update()
    {
        var mousePos = Input.mousePosition;
        mousePos.z = MouseRange;
        Vector3 CursorPosition = cam.ScreenToWorldPoint(mousePos);

        Vector3 Center = new Vector3((Target.position.x + CursorPosition.x) / 2 + Offset.x, (Target.position.y + CursorPosition.y) / 2 + Offset.y, Target.position.z + Offset.z);

        transform.position = Vector3.Lerp(transform.position, Center, Time.deltaTime * MovementSpeed);
    }
}

```

**Comment by KowalikJakub** [comment]
Super! Przyda się jako wzór 👍

**Comment by MartinWoad** [comment]
A tak z ciekawości, jest na Unity konwencja, aby nie obudowywać pól publicznych we właściwości? Bo trochę to nieeleganckie.

**Comment by KowalikJakub** [comment]
@MartinWoad to mocno zależy, od tego czy faktycznie potrzebujesz właściwości. Czasem jest tak że udostępniasz pole bo zwyczajnie nie potrzebujesz żadnej logiki przy zwracaniu i ustawianiu wartości danego pola(lub na przykład obliczeń które są wykonywane w oparciu o stan obiektu). 
Z drugiej strony niby pozwala to na schowaniu pól przed użytkownikiem (czyli super bo robimy hermetyzację) ale są języki obiektowe które wszystko przechowują w postaci publicznych pól/właściwości (różnica jest wtedy trochę rozmyta między tymi pojęciami).

Kończąc wywód, zacytuję kogoś(?nie pamiętam czyje to było?) "Jeśli myślisz że będziesz tego potrzebować w przyszłości to prawdopodobnie nie będziesz." 
Jeśli będzie potrzebne to wtedy można dodać 😃

**Comment by KowalikJakub** [comment]
https://assetstore.unity.com/packages/tools/camera/ez-camera-shake-33148

Skorzystam z tego i umieszczę odpowiedni komponent na kamerze.
