### ISSUE TITLE
Implementacja broni Raycastowej

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#66]
Zaimplementować metodę `Attack` w klasie `RaycastGunViewModel`

**Comment by Kodeman010** [comment]
Obecny diagram UML

![weaponsystemfinished 1](https://user-images.githubusercontent.com/20133604/50226697-2a420380-03a4-11e9-92a4-d148a68ddbb9.jpg)

Rzeczy na które warto zwrócić uwagę:

- Wszystkie klasy niezwiązane z Raycastem są tymczasowe. W momencie implementacji zostaną poprawione.

- Usunięto IAttackable, gdyż nie widzę potrzeby używania tego. 

- Kopie wszystkich zmiennych ze ScriptableObject, będą istnieć w czystej klasie C#. ScriptableObject pozwoli na dostęp do domyślnych zmiennych, natomiast kopie będzie można edytować np. wielkość magazynka, jeśli otrzymamy odpowiedni bonus.

- Absolutnie wszystkie zmienne bezpośrednio związane z bronią, poza referencjami do komponentów znajdują się w modelu. Nawet timery. Domyślam się, że czas dostępu do zmiennej w innym skrypcie jest dłuższy, ale tak jest wszystko lepiej uporządkowane moim zdaniem.

**Comment by KowalikJakub** [comment]
Dobra branch zmergowany więc tu zamykam
