### ISSUE TITLE
[Propozycja] Nowa postać

### ISSUE THREAD

**Issue by KowalikJakub** [Sweaty-Bacon-Ducks/Steamy#67]
Tak jak wspomniałem na discordzie opis postaci: 
Wysoka szczupła postać w poszarpanym smokingu z cylindrem (nakryciem głowy). Połowa ciała tej postaci to elementy mechaniczne a druga to jakaś forma magii (np. w miejsce ręki ludzkiej jest taki ciemny płomień w kształcie ręki. Głowa tej postaci przypominałaby czaszke ludzką.

Myślę że fajnie mogłaby urozmaicić klimat gry o elementy magiczne.

**Comment by Kodeman010** [comment]
Kilka przykładowych pomysłów. Zachęcam do dyskusji nad każdym, ale przyda się wzór klas postaci, żeby modyfikować:

Snajperka:
Scout/Glass cannon
mało hp, szybka, zwiększona wysokość skoku, 
możliwość odbicia się od ścian jeszcze wyżej.

Commando:
po wciśnięciu odpowiedniego przycisku strzela bombą,
jest na nią odporny, ale może strzelić sobie pod nogi, aby się
wystrzelić w powietrze. Ma możliwość lewitacji z horyzontalnym poruszaniem się przez krótką chwilę,
aby mógł trafić tam gdzie chciał

Inżynier:
Podwójny skok, strzelba. Dla dalszych celów granaty.

Proponuję zmienić nazwę issue na "Propozycje postaci" bo w sumie wszystkie są nowe.
