### ISSUE TITLE
Ustalić najlepszy sposób przechowywania danych w modelach

### ISSUE THREAD

**Issue by Kodeman010** [Sweaty-Bacon-Ducks/Steamy#81]
Na ten moment każda zmienna w modelach istnieje w postaci obiektu implementującego interfejs INotifyPropertyChanged, generuje to za dużo kodu.

**Comment by KowalikJakub** [comment]
Tutaj proponuję albo własną implementację wzorca obserwator lub skorzystanie z biblioteki do programowania reaktywnego: [na przykład.](https://assetstore.unity.com/packages/tools/integration/unirx-reactive-extensions-for-unity-17276?fbclid=IwAR1QbC8VN-pYg5a7IhTpc9XWDbJ6N-yAWbOtbGhcadunk7O1PHol59QMRTU)

**Comment by Kodeman010** [comment]
Problem został rozwiązany.
